audit_header: false
title: Portland Real Estate Journal
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Nick Shivers
  license_number:
  about_markdown: |
      As a principal broker in the top 1% of realtors nationwide, Nick Shivers leads the Nick Shivers Team at Keller Williams Realty Portland Central. His 18 years in the Portland Metro and Southwest Washington real estate markets has allowed him the privilege to serve thousands of clients. Our Mission is Serving People Saving Kids all by selling real estate. This mission has served us well by partnering with our clients through Sell a Home Save a child, something we co-founded. We have had the incredible opportunity to make a difference in the lives of hundreds of children. By donating a percentage of every closing, we are impacting the lives of children and building a brighter tomorrow.

  market: Portland Metro & Southwest Washington
  brand: The Nick Shivers Team
  brokerage: Keller Williams Realty Portland Central
  address: 6400 SE Lake Road, Suite 200 Portland, OR 97222
  address2: 5403 E Mill Plain Blvd. Vancouver, WA 98661
  phone: 866-596-NICK (6425)
  phone_type:
  phone2:
  phone2_type:
  email: sold@westonepros.com
  url: http://nickshivers.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808600';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.findhomesinpdx.com/values
  second_CTA_text: Home Search
  second_CTA_URL: http://www.findhomesinpdx.com/area/all

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.findhomesinpdx.com/values

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.findhomesinpdx.com/area/all

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/nickshiversteam
  linkedin_url: https://www.linkedin.com/in/nickshivers/
  youtube_url: https://www.youtube.com/channel/UCzKBdXDqBl5l47xRdvydgfQ?view_as=subscriber
  twitter_url: https://twitter.com/nickshivers
  instagram_url: https://www.instagram.com/westonepropertiesgroup/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Nick-Shivers-Team/
  trulia_url: https://www.trulia.com/profile/nick-shivers-agent-portland-or-zgmw21g9/overview
  yelp_url: https://www.yelp.com/biz/westone-properties-group-keller-williams-realty-portland?osq=west+one+properties
  podcast_url:

podcast:
  title: Serving People, Saving Kids by Selling Real Estate Video Blog with Nick Shivers
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#000000'
  theme_color: '#E31D1A'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
